### ISSUE TITLE
Internationalization impossible with choice names?

### ISSUE THREAD

**Issue by dokterbob** [bigjason/django-choices#2]
Looking at your code example it seems the fact that the property name declares the string rendering of the choice, which is a pity as this makes it impossible (or at least very hard) to make them translatable.

A proper solution might be to do it the other way around, making it look somewhat like this:

    class PersonType(DjangoChoices):
        c = ChoiceItem(_('Customer'))
        e = ChoiceItem(_('Employee'))
        g = ChoiceItem(_('Groundhog'))

**Comment by sergei-maertens** [comment]
@dokterbob is this still relevant in any way? If so, could you clarify use cases, as I don't completely understand the issue at hand here. If it's obsolete, I'll just close this issue to clean up a bit.

**Comment by marcogh** [comment]
Just to complete: you can use the label.

```
class Status(DjangoChoices):
        open = ChoiceItem(0,label=_("Open"))
        released = ChoiceItem(1,label=_("Released"))
        closed = ChoiceItem(3,label=_("Closed"))
```
