### ISSUE TITLE
Active maintainer needed

### ISSUE THREAD

**Issue by sergei-maertens** [bigjason/django-choices#22]
From the time it takes before PR's get noticed, and even worse, to upload new versions to PyPI, I think it's clear that is project can be considered abandoned by @bigjason. @dokterbob can still be reached, but he has no PyPI privileges and from what I understand also a lack of time to really support this project.

So, I'd like to volunteer to take over this project's maintenance. Unless @bigjason contacts me (I've tried contacting him already, with no avail), in the coming week I'll make an official fork of this repo and upload to PyPI under a slightly different name (probably django-choices2). I would then ask @dokterbob to change the readme (or accept a PR) to point people from this repo to the maintained version.

The current PyPI version will break in Django 1.9, would be a shame for this project to go away since it's really useful for clear Choices.

**Comment by bigjason** [comment]
I am sorry I didn't see this @sergei-maertens. I haven't written a line of python in over 4 years so I am not really a good choice. If you are still interested I will grant you access and if you can tell me how I will give you PyPi push rights.

**Comment by sergei-maertens** [comment]
I'll send you an e-mail in a moment to the gmail address in your profile

**Comment by dokterbob** [comment]
Great to hear django-choices is once again alive. Thanks Sergei - and thanks Jason for opening up the PyPI repo.
