### ISSUE TITLE
Cannot install django-choices due to __version__ import that was added setup.py

### ISSUE THREAD

**Issue by ishirav** [bigjason/django-choices#25]
When running `pip install django-choices` in a clean virtualenv I'm getting this error:
```
  Downloading django-choices-1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-EUbJR5/django-choices/setup.py", line 11, in <module>
        from djchoices import __version__
      File "djchoices/__init__.py", line 1, in <module>
        from djchoices.choices import ChoiceItem, DjangoChoices, C
      File "djchoices/choices.py", line 2, in <module>
        from django.core.exceptions import ValidationError
    ImportError: No module named django.core.exceptions
    
```
The traceback shows that setup.py imports `__version__`, and this causes a premature import of djchoices.choices .

The bad import was added here: https://github.com/bigjason/django-choices/commit/9e640f6dd89a9824e0fd8e524a53069f57b7f017

I think that if you want to import the version in setup.py, you should move it to a separate file (one that does not cause djchoices.choices to get imported)

**Comment by sergei-maertens** [comment]
Indeed, this has been on my to-fix list for a few days as I ran into it myself recently. It happens because in `__init__.py` the api is imported, which depends on Django in one place (iirc). A temporary work-around is installing Django before installing django-choices.

I will probably put out a fix for this by the end of the week, and move to Tox to run the tests, as that would've been caught by tox. Thanks for the report, I had forgotten about this a bit.

**Comment by ishirav** [comment]
Unfortunately the workaround does not solve my particular problem - it works under virtualenv/pip but not with our company's buildout-based build system.

Perhaps if you move `from django.core.exceptions import ValidationError` from the top of choices.py into the method that actually uses `ValidationError`, it will solve the problem.

It would be greatly appreciated if you could fix it this week... Thanks!

**Comment by sergei-maertens** [comment]
That was my initial idea to fix it, yes. I understand the problem and will fix it asap.

**Comment by sergei-maertens** [comment]
`django-choices==1.4.2` is available in PyPI now, let me know if you run into any more issues
