### ISSUE TITLE
How to use this Choices which need to be translated: _('my string to translate?')

### ISSUE THREAD

**Issue by guettli** [bigjason/django-choices#30]
How to use this Choices which need to be translated?

Example: _('my string to translate?')

Please don't tell me ... but update the docs :-)

Thank you

**Comment by sergei-maertens** [comment]
Does this answer your question: http://django-choices.readthedocs.org/en/latest/choices.html#labels?

**Comment by guettli** [comment]
Yes. Thank you very much.
