### ISSUE TITLE
A method to lookup the label for a ChoiceItem

### ISSUE THREAD

**Issue by tedmiston** [bigjason/django-choices#31]
I attempted to use your library for choices in a Django model field, but ended up rolling back to a more primitive approach.  Here's a (slightly obfuscated) overview of my use case:

```
class User(models.Model):

    class UserType(DjangoChoices):
        Trial = ChoiceItem('T', label='Trial')
        Active = ChoiceItem('A', label='Active')
        Expired = ChoiceItem('E', label='Expired')

    status = models.CharField(max_length=1, choices=UserType.choices,
                              default=UserType.Trial,
                              validators=[UserType.validator])

    ...
```

But I needed a way to represent the status in in a view.

What I'd like to be able to do is something like this:

```
u = User.objects.get(...)
print u.status.label
```

and get:

```
'Expired'
```

I didn't see an intuitive way to do this mentioned in the docs.

Because at view level, I have access to the model field, all I can see is `E`.

So I considered iterating through the dict from `UserType`, but in terms of interface, that felt weird.  I was wondering if there's a better solution or if you've had this use case?

Best,
Taylor

**Comment by sergei-maertens** [comment]
That's actually provided by Django core, see: https://docs.djangoproject.com/en/1.9/ref/models/instances/#django.db.models.Model.get_FOO_display

You can thus use `u.get_status_display()`

**Comment by tedmiston** [comment]
How quickly we forget :).  That's exactly what I was looking for. :+1:

**Comment by sergei-maertens** [comment]
No problem, happy to help.
