### ISSUE TITLE
Confusing ChoiceItem behavior

### ISSUE THREAD

**Issue by megapctr** [bigjason/django-choices#36]
Turns out that values and labels are created differently than I'd expect:
```
class Choices(DjangoChoices):
    foo = ChoiceItem(_("Footastic"))
    bar = ChoiceItem(_("Baraboom"))
```

In this example, `foo` and `bar` are labels and `Footastic` and `Baraboom` are values - I'd expect the opposite behavior.

I also noticed that explicitly passing the label is not enough
```
foo = ChoceItem(label=_("Footastic"))
```
...because then both values and labels are "Footastic"

This is confusing to me, because labels are usually more verbose as well as more prone to change, and theferore they are less suitable for use in code:
```
class PizzaCrust(DjangoChoices):
    extra_thick_chicago_style = ChoiceItem('thick')
```

Why labels, instead of values, are inferred from the attribute name?

**Comment by sergei-maertens** [comment]
The docs clearly state that the first argument is used as value: http://django-choices.readthedocs.io/en/latest/choices.html#basic-usage

The value is what needs to be explicit - you cannot use a number as an attribute name, so the value can not be derived from the attribute name in all cases. Other than that, it's mostly historical behaviour, it's always been like that. I recommend to use the explicit approach: define value and label in the ChoiceItem, and then use the attribute in your code.

The takeaway is that you should _always_ explicitly define the value as first argument. The label can be inferred from the attribute, but it's not internationalized, so be explict there too.

**Comment by megapctr** [comment]
I understand. However, this leads to redundant expressions like `IN_PROGRESS = ChoiceItem('IN_PROGRESS', _("In progress"))`. There is no better way to write this choice, is there?

**Comment by sergei-maertens** [comment]
In that case, no, there isn't.
