### ISSUE TITLE
Use ordered dict for values

### ISSUE THREAD

**Issue by merwok** [bigjason/django-choices#44]
Hello!  The `choices` attribute is a list of tuples that’s convenient for a django model field declaration, but recently I had a need to convert that to an OrderedDict to send it in a JSON response.  I noticed that a dict can be found as the `values` attribute, but it isn’t ordered.

**Comment by sergei-maertens** [comment]
Fixed with https://github.com/bigjason/django-choices/pull/45, thanks!
