### ISSUE TITLE
How to use with localization?

### ISSUE THREAD

**Issue by elcolie** [bigjason/django-choices#49]
How to use with localization?
Suppose I want to localize my choice to my language.
How can I do that?

**Comment by sergei-maertens** [comment]
Do you mean making the choice labels translatable? This is documented [here](http://django-choices.readthedocs.io/en/latest/choices.html#labels)

**Comment by sergei-maertens** [comment]
Closing because of lack of follow up

**Comment by elcolie** [comment]
Sorry for late response. Thank you for the document.
