### ISSUE TITLE
Release __iter__ changes

### ISSUE THREAD

**Issue by nicoknoll** [bigjason/django-choices#61]
Hey, with the merge on November, 2nd (https://github.com/bigjason/django-choices/commit/7e3eb09cb3e499786de5d8ebac7fa7e39d1a1e04) using `FooChoices.choices` became redundant in regards to directly using `FooChoices` as the `__iter__`method is implemented in the metaclass now.

Is there any release for this planned as the version you get with `pip install` is still 1.6.1 without that change?

**Comment by sergei-maertens** [comment]
1.6.2 is now available on PyPI
