### ISSUE TITLE
Upcoming 'native' choices model support in Django 3.0

### ISSUE THREAD

**Issue by rvdrijst** [bigjason/django-choices#65]
It appears the upcoming Django 3.0 release (expected December 2019) will have something very similar built in (although the syntax is slightly different): https://docs.djangoproject.com/en/dev/releases/3.0/#enumerations-for-model-field-choices

I haven't looked into it too deeply but it appears the new built-in functionality can do everything this app does and, well, it comes built-in with Django...

Maybe it's time to retire this app for future Django releases?

At the very least, the docs should start mentioning this when 3.0 lands.

(Of course, for the foreseeable future this is still a very useful app for those that are stuck on older versions!)

**Comment by sergei-maertens** [comment]
Migration documentation: https://django-choices.readthedocs.io/en/latest/migrating.html
