### ISSUE TITLE
Nested choices

### ISSUE THREAD

**Issue by leowonglaw** [bigjason/django-choices#66]
Sometimes a list of choices is wanted to be represented in a nested structure, where a parent choice cointains a group of subchoices. Parent choices are not wanted to be saved in the database, but its end-child choices are.

For example:
- Free
- Reserved
- Ordered:
    - Requested
    - Approved
    - Billed
    - Delivered

Maybe the choices can have different nested structure representations. :no_mouth:

This kind of grouping is wanted to be used into a cascading dropdown.
![image](https://user-images.githubusercontent.com/31283495/67991885-c796d680-fc08-11e9-9518-10b64fdad5c6.png)

**Comment by sergei-maertens** [comment]
I think this is ultimately more of a presentation matter than a core django-choices issue. As you mentioned yourself, the intermediate options are not valid database values.

You could do a setup a la:

```python
class Statuses(DjangoChoices):
    free = ChoiceItem()
    reserved = ChoiceItem()
    requested = ChoiceItem()
    approved = ChoiceItem()
    billed = ChoiceItem()
    delivered = ChoiceItem()

STRUCTURED_CHOICES = {
    "": (Statuses.free, Statuses.reserved),
    "ordered":  (Statuses.requested, Statuses.approved, Statuses.billed, Statuses.delivered),
}
```

And pass the `STRUCTURED_CHOICES` to the template engine or API endpoint.
