### ISSUE TITLE
Django 3.0 Compatibility

### ISSUE THREAD

**Issue by kavdev** [bigjason/django-choices#68]
It'd be nice to get django-choices compatible with django 3.0 until we can provide:
1) options on how to achieve parity with the new native choices classes in django 3.0
2) a forward migration path (with documentation) from django-choices to django native choices

See also https://github.com/bigjason/django-choices/issues/65

Things to fix:

- [x] django 3.0 dropped their vendored version of six [(release notes)](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis).

**Comment by sergei-maertens** [comment]
Indeed - I need to set some time aside for this. Thanks for listing up the tasks, either way!

I've merged your PR, I'll see if I can push it to PyPI later today 😃
